### ISSUE TITLE
Waste incinerator is recognized as a physical process, although it is entered as a plant in wikidata.

### ISSUE THREAD

**Issue by mcliquid** [matkoniecz/OSM-wikipedia-tag-validator#11]
I had changed the entry to subject:*, but that is wrong according to the CS comment. In that case the tool does not recognize the correctness here.

OSM: https://www.openstreetmap.org/way/500323562
Wikidata: https://www.wikidata.org/wiki/Q1424213

**Comment by matkoniecz** [comment]
This one should be fixed already and become unlisted on the update (I will verify that issue and close it one checked)

In this case this qa report was clearly wrong

**Comment by matkoniecz** [comment]
subject: in this case is clearly wrong

**Comment by matkoniecz** [comment]
fixed, should be gone from reports (if report is fully updated after today and it is still there - let me know)
