### ISSUE TITLE
Collection of possible errors in the detection

### ISSUE THREAD

**Issue by mcliquid** [matkoniecz/OSM-wikipedia-tag-validator#13]
Source: https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/%C3%96sterreich%20(Austria).html

1. Tree is a tree but should use subject:*
OSM-Link: https://www.openstreetmap.org/node/9482863971
Wikidata: https://www.wikidata.org/wiki/Q15133783
(I've added "tree" as a category in the meantime, maybe this will fix the issue)

2. Cemetery is a cemetery but should use subject:*
OSM-Link: https://www.openstreetmap.org/way/509472698
Wikidata: https://www.wikidata.org/wiki/Q18147583

3. "false-positive" in "note:wikidata"
I think it shouldn't be an error if a semicolon is used in the note.
OSM-Link: https://www.openstreetmap.org/way/548715211

**Comment by matkoniecz** [comment]
Thanks for reports!

> Cemetery is a cemetery but should use subject:*

This one is case of Wikidata being silly - reported to Wikidata community, will add exception to ignore Wikidata in this cases if noone will fix it soon https://www.wikidata.org/wiki/User:Mateusz_Konieczny/failing_testcases#Cholerafriedhof_Maria_Dreieichen_(Q18147583)_is_a_social_issue,_according_to_Wikidata_ontology

**Comment by matkoniecz** [comment]
> Tree is a tree but should use subject:*

will be fixed on rerun, also was Wikidata fault (added test to prevent regression)

**Comment by matkoniecz** [comment]
> note:wikidata

excluded, will be no longer expected to be a link to valid wikidata - it can have a freeform content

Thanks for reports! All cases are fixed and/or turned into tests that will be fixed.

**Comment by matkoniecz** [comment]
Note that disappearance from reports may be delayed a bit and will not be immediate.
