### ISSUE TITLE
Change reference to Overpass QL file to use `*.overpassql` file extension

### ISSUE THREAD

**Issue by FloEdelmann** [matkoniecz/OSM-wikipedia-tag-validator#16]
Is this line used in the code?

https://github.com/matkoniecz/OSM-wikipedia-tag-validator/blob/cc93f4724414745ca1bff79b02e2013b2c06bda1/maproulette_challenge_creation.py#L115

At least there is no data folder in the repository. However, if it's not dead code, could you please change it to use the `*.overpassql` file extension?

See also https://github.com/users/FloEdelmann/projects/2/views/4?pane=info and https://github.com/github/linguist/issues/5890

**Comment by matkoniecz** [comment]
It does not yet works (and is a dead code that hopefully will decompose and fertilize a working script).

This part comes from https://github.com/osmlab/maproulette-python-client/blob/dev/examples/challenge_examples.py#L52

**Comment by matkoniecz** [comment]
Right now it exists mostly to provide syntax hints and makes googling/documentation search more efficient.
