### ISSUE TITLE
Exclude elements linking to sections of a Wikipedia page from "wikipedia wikidata mismatch" check

### ISSUE THREAD

**Issue by ivanbranco** [matkoniecz/OSM-wikipedia-tag-validator#18]
Czesc Mateusz,

wikipedia=* tag syntax allows to link sections of a wiki page with an hashtag: wikipedia=language:page title#section_of_the_page

I guess in these cases is implied that the element isn't notable enough to have an entire Wikipedia page for itself (while the Wikidata notability threshold is lower), so they could be treated as false positive. An example: https://www.openstreetmap.org/way/14116957

**Comment by matkoniecz** [comment]
done now, there is now a new `wikipedia wikidata mismatch, wikipedia links to section - high risk of false positive` report hidden by default

note that public report is not yet updated as I regenerate report after external HDD failure
