### ISSUE TITLE
False positive when wikipedia=* links to a redirect page linked to wikidata

### ISSUE THREAD

**Issue by Danysan1** [matkoniecz/OSM-wikipedia-tag-validator#8]
A false positive "wikipedia wikidata mismatch" is generated for elements where
* the element has both wikidata=* and wikipedia=*
* the wikipedia page is a redirect
* **the wikidata entity correctly points to the same (redirect) wikipedia page**

An example is [this element](https://www.openstreetmap.org/node/1426262544):
* the element points to [Q18438710](https://www.wikidata.org/wiki/Q18438710) and [it:Savazza](https://it.wikipedia.org/w/index.php?title=Savazza&redirect=no)
* **The wikidata entity links to the same wikipedia (redirect) page**
* The wikipedia page redirects to [it:Monterenzio#Savazza_-_Cassano](https://it.wikipedia.org/wiki/Monterenzio#Savazza_-_Cassano) which is linked to [Q94968](https://www.wikidata.org/wiki/Q94968)

Yet, the element is listed [in the wikipedia wikidata mismatch section of the report](https://matkoniecz.github.io/OSM-wikipedia-tag-validator-reports/Italia%20(Italy,%20W%C5%82ochy):%20Emilia-Romagna%20(Emilia-Romania).html#wikipedia%20wikidata%20mismatch) with the description

> wikidata and wikipedia tags link to a different objects (Q18438710 vs (missing) wikidata id assigned to linked Wikipedia article) Note that this OSM object has wikipedia tag that links redirect ('Savazza' to 'Monterenzio').

For reference here are the guidelines from [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:wikipedia):

> * When you link to a section of a page, the spaces must be replaced by underscores. `wikipedia=language:page title#section_of_the_page`. Generally, do not do this; look for a redirect to that section whose full title matches the item you are linking from.
> * ...
> * Avoid redirects, for example, link to [`de:Frashër`](https://en.wikipedia.org/wiki/de:Frash%C3%ABr) and not to [`de:Frasher`](https://en.wikipedia.org/wiki/de:Frasher) (which is a redirect).

This is not really clear, this seems a contraddiction, it seems it means that redirects should be used only when you need to a redirect to a section but avoided when an article on the item already exists

**Comment by matkoniecz** [comment]
Thanks for report, that deserves a special case (when I was writing it I was unaware about linking with redirect pages - that may be even invented after I wrote that part of checker).

Again thanks for beautiful report! I will add a test to handle this and try to fix it in some nice way.

**Comment by matkoniecz** [comment]
Should be now working correctly!

**Comment by matkoniecz** [comment]
Please let me know if it is broken again. Or if you spot anything else problematic.
